export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
export const FETCH_USERS_COMPLETED = 'FETCH_USERS_COMLETED'

export const FORCE_AUTH = 'FORCE_AUTH'
export const LOG_IN = 'LOG_IN'
